### ISSUE TITLE
Blocking hostnames that don't provide DoH or DoT

### ISSUE THREAD

**Issue by kimbo** [Sekhan/TheGreatWall#2]
Just noticed you have Verisign on there. AFAIK, they don't offer DoT or DoH. Is the idea to block any public DNS service, or just DoT and DoH?

**Comment by Sekhan** [comment]
For the moment, this list only concern services that provide DoH (and eventually DoT, even if it's not mandatory since you can easily block them with port 853).

Indeed, it doesn't seem to be the case for Yandex either (I'll check again in the future if I haven't missed other one). I've removed them. Thanks for your feedback !
